api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "JILL Profile Dashboard"
handle = "jill-account-home"

[[extensions.targeting]]
target = "customer-account.profile.block.render"
module = "./src/AccountHome.jsx"

[extensions.capabilities]
api_access = true
