api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Coupons"
handle = "jill-account-coupons"

[[extensions.targeting]]
target = "customer-account.page.render"
module = "./src/Coupons.jsx"

[extensions.capabilities]
api_access = true
